/**
 * Fixture adapter for the panel's backend interface.
 *
 * Same eleven methods as frontend/src/backend.js, served from
 * dev/fixtures/remotes.json (generated by scripts/make_fixture.py from
 * the real layouts). State is kept in memory so saves round-trip within
 * a session. `subscribeRemoteEvents` replays the fixture's events on a
 * timer; `subscribeEntity` flips the light every few seconds so the live
 * state pane has something to show.
 *
 * Importable in Node (tests) and in the browser (dev/shim.mjs).
 */
import { BackendError } from "../custom_components/remote_studio/frontend/src/backend.js";

const clone = (v) => (v === undefined ? v : JSON.parse(JSON.stringify(v)));

export function createFixtureBackend(fixture, { eventIntervalMs = 4000, stateIntervalMs = 5000 } = {}) {
  const data = clone(fixture);
  const notFound = (what) => new BackendError(`Unknown ${what}`, `${what}_not_found`);

  const device = (deviceId) => {
    const d = data.devices[deviceId];
    if (!d) throw notFound("device");
    return d;
  };

  const refreshTargets = (deviceId) => {
    const remote = data.remotes.find((r) => r.device_id === deviceId);
    if (!remote) return;
    const ids = [];
    for (const g of Object.values(device(deviceId).groups)) {
      const eid = g.target?.entity_id;
      for (const e of [].concat(eid || [])) if (e && !ids.includes(e)) ids.push(e);
    }
    remote.targets = ids;
  };

  return {
    async listRemotes() {
      return clone({
        version: data.version,
        remotes: data.remotes,
        candidates: data.candidates,
        definitions: data.definitions,
      });
    },

    async getVersion() {
      return data.version;
    },

    async getRemote(deviceId, definitionId) {
      const d = device(deviceId);
      if (!definitionId) return clone(d);
      const def = data.definitions.find((x) => x.id === definitionId);
      if (!def) throw notFound("definition");
      return clone({ ...d, definition: def, svg: def.svg });
    },

    async setGroup(deviceId, groupId, fields) {
      const d = device(deviceId);
      const defaults = d.group_defaults;
      const next = {
        ...defaults,
        target: fields.target ?? null,
        dim_step: fields.dim_step ?? defaults.dim_step,
      };
      if (fields.scene_color !== undefined) next.scene_color = fields.scene_color;
      if (fields.scene_brightness !== undefined) next.scene_brightness = fields.scene_brightness;
      next.scene_is_default =
        next.scene_color == null && next.scene_brightness === defaults.scene_brightness;
      const isDefault =
        !next.target && next.dim_step === defaults.dim_step && next.scene_is_default;
      if (isDefault) delete d.groups[groupId];
      else d.groups[groupId] = next;
      refreshTargets(deviceId);
      return { ok: true, group: clone(next) };
    },

    async setOverride(deviceId, buttonId, stateId, actions) {
      const d = device(deviceId);
      if (actions && actions.length) {
        (d.overrides[buttonId] ||= {})[stateId] = clone(actions);
      } else if (d.overrides[buttonId]) {
        delete d.overrides[buttonId][stateId];
        if (!Object.keys(d.overrides[buttonId]).length) delete d.overrides[buttonId];
      }
      return { ok: true };
    },

    async setPairing(deviceId, definitionId) {
      const d = data.devices[deviceId];
      if (d) d.paired_definition_id = definitionId || null;
      return { ok: true };
    },

    async triggerButton(deviceId, buttonId, stateId) {
      const d = device(deviceId);
      const button = d.definition.buttons.find((b) => b.id === buttonId);
      const state = button?.states.find((s) => s.id === stateId);
      if (!state) throw notFound("state");
      const override = d.overrides[buttonId]?.[stateId];
      const group = d.groups[button.group];
      const fired = Boolean(override?.length || (state.role !== "none" && group?.target));
      return { ok: true, fired };
    },

    async testAction(actions) {
      if (!Array.isArray(actions) || !actions.length) {
        throw new BackendError("Nothing to run", "action_failed");
      }
      return { ok: true };
    },

    async enableEntities(entityIds) {
      for (const d of Object.values(data.devices)) {
        d.health.disabled_entities = d.health.disabled_entities.filter(
          (e) => !entityIds.includes(e.entity_id),
        );
      }
      return { ok: true, enabled: [...entityIds], failed: [] };
    },

    async subscribeRemoteEvents(cb) {
      let i = 0;
      const events = data.events || [];
      if (!events.length) return () => {};
      const timer = setInterval(() => {
        cb(clone(events[i % events.length]));
        i += 1;
      }, eventIntervalMs);
      return () => clearInterval(timer);
    },

    async subscribeEntity(entityId, cb) {
      const st = data.states[entityId];
      if (!st) return () => {};
      const timer = setInterval(() => {
        if (st.entity_id.startsWith("light.") || st.entity_id.startsWith("switch.")) {
          st.state = st.state === "on" ? "off" : "on";
          st.last_changed = new Date().toISOString();
          cb(clone(st));
        }
      }, stateIntervalMs);
      return () => clearInterval(timer);
    },

    // Test/dev hook: the current in-memory fixture.
    _data: data,
  };
}
